<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Benjamin Egan" />


<title>Commentary on Lab 12 - Smoking during pregnancy</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="Aesthetics.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Benjamin Egan's Labs</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About Me</a>
</li>
<li>
  <a href="lab1.html">Lab 1</a>
</li>
<li>
  <a href="lab2.html">Lab 2</a>
</li>
<li>
  <a href="lab3.html">Lab 3</a>
</li>
<li>
  <a href="lab4.html">Lab 4</a>
</li>
<li>
  <a href="lab5.html">Lab 5</a>
</li>
<li>
  <a href="lab6.html">Lab 6</a>
</li>
<li>
  <a href="lab7.html">Lab 7</a>
</li>
<li>
  <a href="lab8.html">Lab 8</a>
</li>
<li>
  <a href="lab9.html">Lab 9</a>
</li>
<li>
  <a href="lab10.html">Lab 10</a>
</li>
<li>
  <a href="lab11.html">Lab 11</a>
</li>
<li>
  <a href="lab12.html">Lab 12</a>
</li>
<li>
  <a href="lab13.html">Lab 13</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Commentary on Lab 12 - Smoking during
pregnancy</h1>
<h4 class="author">Benjamin Egan</h4>

</div>


<div id="created-4142025" class="section level4">
<h4>Created 4/14/2025</h4>
<p>Link to the assignment page, at the time of creation: <a
href="https://web.archive.org/web/20250414135227/https://datascience4psych.github.io/DataScience4Psych/lab12.html"
class="uri">https://web.archive.org/web/20250414135227/https://datascience4psych.github.io/DataScience4Psych/lab12.html</a></p>
<p>Link to assignment page as of April 25 2025: <a
href="https://datascience4psych.github.io/DataScience4Psych/lab12.html"
class="uri">https://datascience4psych.github.io/DataScience4Psych/lab12.html</a></p>
</div>
<div id="commentary-on-lab-12" class="section level2">
<h2>Commentary on Lab 12</h2>
<p>I will be walking through lab 12, designed to practice data
manipulation, visualization, hypothesis testing, and calculating
confidence intervals. Questions and comments from the lab that I will be
addressing will be in bold. My commentary will always have “Commentary:”
infront. This can make it easier to quickly skim through the document by
searching for the word commentary.</p>
<p>Loading the data</p>
<pre class="r"><code>data(ncbirths)
#view(ncbirths)</code></pre>
<div
id="before-analyzing-any-new-dataset-its-important-to-get-to-know-your-data.-start-by-summarizing-the-variables-and-determining-if-their-data-type.-are-they-categorical-are-they-numerical-for-numerical-variables-check-for-outliers.-if-you-arent-sure-or-want-to-take-a-closer-look-at-the-data-create-a-graph."
class="section level4">
<h4>Before analyzing any new dataset, it’s important to get to know your
data. Start by summarizing the variables and determining if their data
type. Are they categorical? Are they numerical? For numerical variables,
check for outliers. If you aren’t sure or want to take a closer look at
the data, create a graph.</h4>
<pre class="r"><code>summary(ncbirths)</code></pre>
<pre><code>##       fage            mage            mature        weeks             premie   
##  Min.   :14.00   Min.   :13   mature mom :133   Min.   :20.00   full term:846  
##  1st Qu.:25.00   1st Qu.:22   younger mom:867   1st Qu.:37.00   premie   :152  
##  Median :30.00   Median :27                     Median :39.00   NA&#39;s     :  2  
##  Mean   :30.26   Mean   :27                     Mean   :38.33                  
##  3rd Qu.:35.00   3rd Qu.:32                     3rd Qu.:40.00                  
##  Max.   :55.00   Max.   :50                     Max.   :45.00                  
##  NA&#39;s   :171                                    NA&#39;s   :2                      
##      visits            marital        gained          weight      
##  Min.   : 0.0   not married:386   Min.   : 0.00   Min.   : 1.000  
##  1st Qu.:10.0   married    :613   1st Qu.:20.00   1st Qu.: 6.380  
##  Median :12.0   NA&#39;s       :  1   Median :30.00   Median : 7.310  
##  Mean   :12.1                     Mean   :30.33   Mean   : 7.101  
##  3rd Qu.:15.0                     3rd Qu.:38.00   3rd Qu.: 8.060  
##  Max.   :30.0                     Max.   :85.00   Max.   :11.750  
##  NA&#39;s   :9                        NA&#39;s   :27                      
##  lowbirthweight    gender          habit          whitemom  
##  low    :111    female:503   nonsmoker:873   not white:284  
##  not low:889    male  :497   smoker   :126   white    :714  
##                              NA&#39;s     :  1   NA&#39;s     :  2  
##                                                             
##                                                             
##                                                             
## </code></pre>
<p>By using summary(), I know there are 7 categorical variables and 6
numerical variables.</p>
<p>I way overengineered looking for outliers, getting help from Chat
GPT.</p>
<pre class="r"><code>base_outlier_check &lt;- function(variable) {
  ncbirths %&gt;%
  ggplot(aes(x = {{ variable }})) +
    geom_histogram(stat = &quot;count&quot;) +
    labs(title = rlang::as_label(rlang::enquo(variable)), y = NULL)
}

map(c(&quot;fage&quot;, &quot;mage&quot;,&quot;weeks&quot;,&quot;visits&quot;,&quot;gained&quot;,&quot;weight&quot;), ~ base_outlier_check(!!sym(.x)))</code></pre>
<pre><code>## [[1]]</code></pre>
<p><img src="lab12_files/figure-html/outlier%20check-1.png" width="672" /></p>
<pre><code>## 
## [[2]]</code></pre>
<p><img src="lab12_files/figure-html/outlier%20check-2.png" width="672" /></p>
<pre><code>## 
## [[3]]</code></pre>
<p><img src="lab12_files/figure-html/outlier%20check-3.png" width="672" /></p>
<pre><code>## 
## [[4]]</code></pre>
<p><img src="lab12_files/figure-html/outlier%20check-4.png" width="672" /></p>
<pre><code>## 
## [[5]]</code></pre>
<p><img src="lab12_files/figure-html/outlier%20check-5.png" width="672" /></p>
<pre><code>## 
## [[6]]</code></pre>
<p><img src="lab12_files/figure-html/outlier%20check-6.png" width="672" /></p>
<p>mage could have an outlier on the upper end. I don’t think weeks has
an outlier, even though it’s skewed left. visits may have an outlier on
the upper end. weight might have one or two on the upper end, but it’s
skewed left.</p>
<p>Commentary: This was pretty basic, and I made it way harder than it
had to be. This could, however, be a good moment to throw it back to lab
8 and show a way to use a function. I would just guide them on the
labeling bit, as it can be tricky. You can use do what I did and use
base R. This allows you to input all the variables at once using map().
If you use tidyverse for the label and use
deparse(substitute(variable)), you have to individually input each
function and cannot mass input.</p>
</div>
<div
id="what-are-the-cases-in-this-data-set-how-many-cases-are-there-in-our-sample"
class="section level4">
<h4>1. What are the cases in this data set? How many cases are there in
our sample?</h4>
<pre class="r"><code>ncbirths %&gt;%
nrow()</code></pre>
<pre><code>## [1] 1000</code></pre>
<p>There are 1000 cases, as each row represents an individual birth.</p>
</div>
<div
id="create-a-filtered-data-frame-called-ncbirths_white-that-contains-data-only-from-white-mothers.-then-calculate-the-mean-of-the-weights-of-their-babies."
class="section level3">
<h3>2. Create a filtered data frame called ncbirths_white that contains
data only from White mothers. Then, calculate the mean of the weights of
their babies.</h3>
<pre class="r"><code>ncbirths_white &lt;- ncbirths %&gt;%
  filter(whitemom == &quot;white&quot;)

mean(ncbirths_white$weight)</code></pre>
<pre><code>## [1] 7.250462</code></pre>
<p>The mean weight of the white babies is 7.25 lbs. The hypothesis
states that there is no change in weight since 1995 (i.e. mu = 7.43).
Since white babies weigh less, we need to figure out if this is a
meaningful difference.</p>
<p>Commentary: You/someone else included a note in the code that says
“Mason make this clearer to why we need to actually do this.” I don’t
think you need to explain, if they watched the videos or viewed the
slides. What I would like more clarification on is question 3. My
imagination for an answer is to create a visual for the data and see if
mu falls within the CI in this sample.</p>
</div>
<div
id="are-the-criteria-necessary-for-conducting-simulation-based-inference-satisfied-explain-your-reasoning."
class="section level3">
<h3>3. Are the criteria necessary for conducting simulation-based
inference satisfied? Explain your reasoning.</h3>
<pre class="r"><code>ncbirths_white %&gt;%
  ggplot(aes(
    x = weight
  ))+
  geom_histogram(stat = &quot;count&quot;, color = &quot;blue&quot;)+
  geom_vline(xintercept = 7.43, 
               color = &quot;white&quot;, 
               linetype = &quot;dashed&quot;)+
   geom_vline(xintercept = 7.25, 
               color = &quot;red&quot;, 
               linetype = &quot;dashed&quot;)+
  annotate(&quot;text&quot;, 
           x = 4, y = Inf, 
           label = &quot;White = Mu, Red = Sample mean&quot;, 
           vjust = 2, 
           color = &quot;black&quot;)+
  theme_bw()+
  labs(
    x = &quot;Weight in lbs&quot;,
    y = NULL,
    title = &quot;Distriubtion of weight&quot;,
    subtitle = &quot;How does this shape up to the popluation mean?&quot;
  )</code></pre>
<pre><code>## Warning in geom_histogram(stat = &quot;count&quot;, color = &quot;blue&quot;): Ignoring unknown
## parameters: `binwidth`, `bins`, and `pad`</code></pre>
<p><img src="lab12_files/figure-html/should%20we%20baby%20weight%20hypothesis%20test-1.png" width="672" />
Based on this graph, I would guess that we probably would fail to
reject, considering the mean weight is so close to the population
weight. But this is only one sample, so it makes sense to use
bootstrapping to better estimate the difference.</p>
</div>
</div>
<div
id="run-the-appropriate-hypothesis-test-visualize-the-null-distribution-calculate-the-p-value-and-interpret-the-results-in-the-context-of-the-data-and-the-hypothesis-test."
class="section level2">
<h2>4. Run the appropriate hypothesis test, visualize the null
distribution, calculate the p-value, and interpret the results in the
context of the data and the hypothesis test.</h2>
<div id="steps-for-hypothesis-testing" class="section level4">
<h4>Steps for hypothesis testing</h4>
<ul>
<li>take a bootstrap sample of from the original sample</li>
<li>calculate this bootstrap sample’s mean</li>
<li>repeat these two steps a large number of times to create a bootstrap
distribution of means centered at the observed sample mean,</li>
<li>shift this distribution to be centered at the null value by
subtracting / adding X to all bootstrap mean (X = difference between
mean of bootstrap distribution and null value)</li>
<li>calculate the p-value as the proportion of bootstrap samples that
yielded a sample mean at least as extreme as the observed sample
mean.</li>
</ul>
<pre class="r"><code>seed</code></pre>
<pre><code>## NULL</code></pre>
<pre class="r"><code>white_weight_bootstrap &lt;- ncbirths_white %&gt;%
  specify(response = weight) %&gt;% 
  generate(reps = 15000, type = &quot;bootstrap&quot;) %&gt;% 
  calculate(stat = &quot;mean&quot;)

mean_white_weight_boostrap &lt;- mean(white_weight_bootstrap$stat)

white_weight_bootstrap &lt;-  white_weight_bootstrap %&gt;%
  mutate(Cstat = (stat - 7.43))

white_weight_bootstrap %&gt;%
  summarize(lower = quantile(Cstat, 0.025),
            upper = quantile(Cstat, 0.975))</code></pre>
<pre><code>## # A tibble: 1 × 2
##    lower   upper
##    &lt;dbl&gt;   &lt;dbl&gt;
## 1 -0.282 -0.0763</code></pre>
<pre class="r"><code>white_weight_bootstrap %&gt;%
  ggplot(mapping = aes(x = Cstat)) +
  geom_histogram() +
  labs(title = &quot;Bootstrap distribution of means for white baby weight&quot;, y = NULL, x = &quot;Means&quot;)+
  geom_vline(xintercept = 0, 
               color = &quot;black&quot;, 
               linetype = &quot;solid&quot;)+
  annotate(&quot;text&quot;, 
           x = -.03, y = Inf, 
           label = &quot;Pop mean&quot;, 
           vjust = 2, 
           color = &quot;black&quot;)+
  geom_vline(xintercept = -0.2847633,                 #Lower CI
               color = &quot;blue&quot;, 
               linetype = &quot;dashed&quot;)+
  geom_vline(xintercept = -0.07682038,               #Upper CI
               color = &quot;blue&quot;, 
               linetype = &quot;dashed&quot;)+
  annotate(&quot;text&quot;, 
           x = -0.31, y = Inf, 
           label = &quot;95% CI&quot;, 
           vjust = 2, 
           color = &quot;black&quot;)+
  theme_bw()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with
## `binwidth`.</code></pre>
<p><img src="lab12_files/figure-html/bootstrap%20weight-1.png" width="672" /></p>
<pre class="r"><code># p value
pvalue_white_weight &lt;- white_weight_bootstrap %&gt;%
  mutate(sig = case_when(
    stat &lt;= mean_white_weight_boostrap ~ 1,
    stat &gt;= mean_white_weight_boostrap ~ 0,
  ))


white_weight_sig &lt;- pvalue_white_weight %&gt;%
  filter(sig == 1)

count(white_weight_sig)/15000</code></pre>
<pre><code>##           n
## 1 0.4981333</code></pre>
<p>95% CI:(7.145237, 7.35318)</p>
<p>Based on this, it’s clear that the population mean falls outside the
confidence interval. We would reject the null and say that babies’
weight has decreased since 1995.</p>
<p>To calculate the p value, I created a variable that designated
whether the mean in the bootstrap was lower than the observed mean of
7.25. I then divided the number of significant ones by the total number
of observations in the bootstrap to get a p of .50, indicating that the
sample means should not be significantly different from the popluation
mean.</p>
<p>Commentary: I would break out the step by step instructions. It was
easy to figure out how to make the graph based on the slides, so maybe
add in a tip to go back and reference the slides? I will say that I
believe I messed this up somewhere along the way, as my p value should
be reflective of the fact that the population mean of 7.43 is way
outside the confidence interval I estimated. If I had to guess, I either
messed up the calculation of the p value or my interpretation of the p
value.</p>
</div>
</div>
<div id="baby-weight-vs-smoking" class="section level2">
<h2>Baby Weight vs Smoking</h2>
<div
id="make-side-by-side-box-plots-displaying-the-relationship-between-habit-and-weight.-what-does-the-plot-highlight-about-the-relationship-between-these-two-variables"
class="section level4">
<h4>5. Make side-by-side box plots displaying the relationship between
habit and weight. What does the plot highlight about the relationship
between these two variables?</h4>
<p>Commentary: I would specify here if you want us to continue to
utilize only White babies or all babies. I am assuming you want us to
use all babies here.</p>
<pre class="r"><code>ncbirths %&gt;%
  ggplot(aes(
    x = habit,
    y = weight
  ))+
    geom_boxplot()+
  labs(
    x = &quot;Smoking Status&quot;,
    y = &quot;Weight in lbs&quot;,
    title = &quot;Relationship between smoking and weight&quot;
  )</code></pre>
<p><img src="lab12_files/figure-html/box%20plot%20habit%20weight-1.png" width="672" /></p>
<p>It appears that there are a lot of underweight babies for non-smokers
compared to smokers. This could be due to sample differences, as
non-smokers could have more babies overall.</p>
</div>
<div
id="before-continuing-create-a-cleaned-version-of-the-dataset-by-removing-any-rows-with-missing-values-for-habit-or-weight.-name-this-version-ncbirths_clean."
class="section level4">
<h4>6. Before continuing, create a cleaned version of the dataset by
removing any rows with missing values for habit or weight. Name this
version ncbirths_clean.</h4>
<pre class="r"><code>ncbirths_clean &lt;- ncbirths %&gt;%
  filter(!habit == &quot;NA&quot;)

ncbirths_clean %&gt;%
  ggplot(aes(
    x = habit,
    y = weight
  ))+
    geom_boxplot()+
  labs(
    x = &quot;Smoking Status&quot;,
    y = &quot;Weight in lbs&quot;,
    title = &quot;Relationship between smoking and weight&quot;
  )</code></pre>
<p><img src="lab12_files/figure-html/clean%20smoking%20data-1.png" width="672" /></p>
<p>We can see that we cleaned the data to filter out the person who
didn’t answer the smoking question.</p>
</div>
<div
id="calculate-the-observed-difference-in-means-between-the-baby-weights-of-smoking-and-non-smoking-mothers."
class="section level4">
<h4>7. Calculate the observed difference in means between the baby
weights of smoking and non-smoking mothers.</h4>
<pre class="r"><code>ncbirths_clean %&gt;%
  group_by(habit) %&gt;%
  summarize(mean_weight = mean(weight))</code></pre>
<pre><code>## # A tibble: 2 × 2
##   habit     mean_weight
##   &lt;fct&gt;           &lt;dbl&gt;
## 1 nonsmoker        7.14
## 2 smoker           6.83</code></pre>
<p>We can see that non-smoking babies have a higher mean weight that
smoking babies.</p>
</div>
<div
id="write-the-hypotheses-for-testing-if-the-average-weights-of-babies-born-to-smoking-and-non-smoking-mothers-are-different."
class="section level4">
<h4>8. Write the hypotheses for testing if the average weights of babies
born to smoking and non-smoking mothers are different.</h4>
<p>H0: Mu1 - Mu2 = 0 OR Mu1 = Mu2 (No difference between smokers and
non-smokers on baby weight)</p>
<p>H1: Mu1 - Mu2 ≠ 0 OR Mu1 ≠ Mu2 (There is a difference between smokers
and non-smokers on baby weigh)</p>
<p>Commentary: I TA for the 312 class and have hypothesis testing
essentially tattooed on my frontal lobe.</p>
</div>
<div
id="run-the-appropriate-hypothesis-test-calculate-the-p-value-and-interpret-the-results-in-context-of-the-data-and-the-hypothesis-test."
class="section level4">
<h4>9. Run the appropriate hypothesis test, calculate the p-value, and
interpret the results in context of the data and the hypothesis
test.</h4>
<pre class="r"><code>#view(ncbirths_clean)

ci_vals &lt;- ncbirths_clean %&gt;%
  group_by(habit) %&gt;%
  summarize(
    mean_weight = mean(weight),
    se = sd(weight) / sqrt(sum(!is.na(weight))),
    lower = mean_weight - 1.96 * se,
    upper = mean_weight + 1.96 * se
  )
ci_vals</code></pre>
<pre><code>## # A tibble: 2 × 5
##   habit     mean_weight     se lower upper
##   &lt;fct&gt;           &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 nonsmoker        7.14 0.0514  7.04  7.25
## 2 smoker           6.83 0.123   6.59  7.07</code></pre>
<p>CI for non-smokers (7.043530, 7.245016) CI for smokers (6.586688,
7.070772)</p>
<pre class="r"><code>ncbirths_clean %&gt;%
ggplot(aes(
  x = weight, 
  fill = habit, 
  color = habit)) +
  geom_density(alpha = 0.4) +
  
  # Add CI
  geom_vline(data = ci_vals, 
             aes(xintercept = lower, 
                 color = habit), 
             linetype = &quot;dashed&quot;) +
  geom_vline(data = ci_vals, 
             aes(xintercept = upper, 
                 color = habit), 
             linetype = &quot;dashed&quot;) +
  scale_color_manual(
    name = &quot;Smoking Status&quot;,
    values = c(&quot;nonsmoker&quot; = &quot;blue&quot;, &quot;smoker&quot; = &quot;red&quot;))+
  scale_fill_manual(
    name = &quot;Smoking Status&quot;,
    values = c(&quot;nonsmoker&quot; = &quot;skyblue&quot;, &quot;smoker&quot; = &quot;pink&quot;))+
  
  #I got some help from ChatGPT to make it better. I clearly could&#39;ve used a string and wrote out the CI, but this looked cooler
  annotate(&quot;text&quot;, 
         x = 2, y = 0.33, hjust = 0, size = 3.5,
         label = paste0(&quot;Non-smoker 95% CI: [&quot;, 
                        round(ci_vals$lower[ci_vals$habit == &quot;nonsmoker&quot;], 2), &quot;, &quot;, 
                        round(ci_vals$upper[ci_vals$habit == &quot;nonsmoker&quot;], 2), &quot;]&quot;),
         color = &quot;blue&quot;) +
annotate(&quot;text&quot;, 
         x = 2, y = 0.30, hjust = 0, size = 3.5,
         label = paste0(&quot;Smoker 95% CI: [&quot;, 
                        round(ci_vals$lower[ci_vals$habit == &quot;smoker&quot;], 2), &quot;, &quot;, 
                        round(ci_vals$upper[ci_vals$habit == &quot;smoker&quot;], 2), &quot;]&quot;),
         color = &quot;red&quot;)+
  
  labs(
    x = &quot;Baby weight in lbs&quot;,
    y = NULL,
    title = &quot;Baby weight distribution based on smoking&quot;
  ) +
  theme_bw()</code></pre>
<p><img src="lab12_files/figure-html/visual%20CI%20for%20smoking-1.png" width="672" /></p>
<p>Based on this graph, it looks like the two distributions heavily
overlap, and there appears to be some basic overlap for the CIs.</p>
<div id="commentary" class="section level5">
<h5>Commentary</h5>
<p>I will admit that I was completely lost on how to get the p value. I
looked back through the class notes and here is what I came up with:</p>
<p>Idea 1: Create the null distribution <br/> I was thinking about
somehow creating the null distribution that assumes the mean difference
is zero. I could possibly do this by somehow bootstrapping the weight
data but telling the simluation that the resulting outcome should be two
stats, one for smokers and one for non-smokers</p>
<p>Idea 2: two boostraps and join <br/> For this, I would filter based
on smoking status. I would then bootstrap for each of the two datasets,
and then join them together. The downside to this is that I don’t know
if I would need to bootstrap the combined bootstraps to truly achieve
what I wanted to do.</p>
<p>Idea 3: cry <br/> No not actually, but I am thinking that I could
somehow create difference scores and bootstrap the difference scores. I
only think this would work if there is equal sample size, which I know
for a fact there isn’t based on the summary() look at the variables.</p>
<p>I’m thinking that I’ll need to use idea one, since I’m not confident
idea 2 would give me the best outcomes.</p>
<pre class="r"><code>seed</code></pre>
<pre><code>## NULL</code></pre>
<pre class="r"><code>smoking_pvalue_test &lt;- ncbirths_clean %&gt;%
  group_by(habit) %&gt;%
  specify(response = weight) %&gt;% 
  generate(reps = 15000, type = &quot;bootstrap&quot;) %&gt;% 
  calculate(stat = &quot;mean&quot;)

head(smoking_pvalue_test)</code></pre>
<pre><code>## Response: weight (numeric)
## # A tibble: 6 × 2
##   replicate  stat
##       &lt;int&gt; &lt;dbl&gt;
## 1         1  7.14
## 2         2  7.09
## 3         3  7.13
## 4         4  7.10
## 5         5  7.09
## 6         6  7.11</code></pre>
<p>Ok so I fought with chat heavily to figure out how to do it this way
via idea 1, and I have zero clue why group_by isn’t doing it’s job. So
now I’ll try idea two, but using chat’s help</p>
<pre class="r"><code># Load necessary libraries
library(dplyr)
library(infer)


# Split the dataset by habit (smoker vs nonsmoker)
smoker_data &lt;- ncbirths_clean %&gt;% filter(habit == &quot;smoker&quot;)
nonsmoker_data &lt;- ncbirths_clean %&gt;% filter(habit == &quot;nonsmoker&quot;)

# Perform bootstrap for smokers
smoker_bootstrap &lt;- specify(smoker_data, response = weight) %&gt;%
  generate(reps = 15000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;)

# Perform bootstrap for non-smokers
nonsmoker_bootstrap &lt;- specify(nonsmoker_data, response = weight) %&gt;%
  generate(reps = 15000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;)

# Combine both bootstrap results into one data frame
white_weight_habit_bootstrap &lt;- bind_rows(
  smoker_bootstrap %&gt;% mutate(habit = &quot;smoker&quot;),
  nonsmoker_bootstrap %&gt;% mutate(habit = &quot;nonsmoker&quot;)
)</code></pre>
<p>I went back and asked it to do it only using the libraries required
thus far.</p>
<pre class="r"><code># Split the dataset by &#39;habit&#39; (smoker vs nonsmoker)
smoker_data &lt;- ncbirths_clean %&gt;% filter(habit == &quot;smoker&quot;)
nonsmoker_data &lt;- ncbirths_clean %&gt;% filter(habit == &quot;nonsmoker&quot;)

# Define a function to perform bootstrapping
bootstrap_mean &lt;- function(data, reps = 15000) {
  # Create bootstrap samples and calculate means
  replicate(reps, {
    sample_data &lt;- sample(data$weight, replace = TRUE)
    mean(sample_data)
  })
}

# Perform bootstrap for smokers
smoker_bootstrap_means &lt;- bootstrap_mean(smoker_data, 15000)

# Perform bootstrap for non-smokers
nonsmoker_bootstrap_means &lt;- bootstrap_mean(nonsmoker_data, 15000)

# Combine both bootstrap results into one data frame
white_weight_habit_bootstrap &lt;- tibble(
  habit = c(rep(&quot;smoker&quot;, 15000), rep(&quot;nonsmoker&quot;, 15000)),
  bootstrap_mean = c(smoker_bootstrap_means, nonsmoker_bootstrap_means)
)</code></pre>
<p>Another attempt using ChatGPT. Here is what I plugged into chat</p>
<p>What if i try creating a loop using for or if or while. The loop
specifies that I filter for only smoker data, simulate 1500, and apply a
categorical variable with the designation “smoker”. I then repeat the
sequence, except I now filter for only nonsmoker data pply a categorical
variable with the designation “nonsmoker”</p>
<p>It gave me a response I didn’t like, and asked “Is it possible to
restructure or recreate the code such that we won’t have to combine the
boostraps and that it will do it all in one go?”</p>
<pre class="r"><code># Set habit groups and number of reps
habits &lt;- c(&quot;smoker&quot;, &quot;nonsmoker&quot;)
n_reps &lt;- 15000

# Initialize an empty tibble to collect all bootstrap results
white_weight_habit_bootstrap &lt;- tibble()

# Loop through both habit groups and perform bootstrap
for (h in habits) {
  
  # Filter the data for the current group
  current_data &lt;- ncbirths_clean %&gt;% filter(habit == h)
  
  # Perform bootstrap in one go (faster than nested loop)
  boot_means &lt;- map_dbl(1:n_reps, ~ mean(sample(current_data$weight, replace = TRUE)))
  
  # Append results directly to the main tibble
  white_weight_habit_bootstrap &lt;- bind_rows(
    white_weight_habit_bootstrap,
    tibble(habit = h, bootstrap_mean = boot_means)
  )
}

# View result ---- view(white_weight_habit_bootstrap)</code></pre>
<p>Commentary: To figure out what is happening with group_by, I
simulated data with extreme means.</p>
<pre class="r"><code>seed</code></pre>
<pre><code>## NULL</code></pre>
<pre class="r"><code>small &lt;- rnorm(100, mean = 10, sd = 5)

dfsmall &lt;- data.frame(
    score = small,
    group = 1
  )

large &lt;- rnorm(100, mean = 1000, sd = 5)

dflarge &lt;- data.frame(
    score = large,
    group = 2
  )

simulation &lt;- full_join(dfsmall,dflarge)</code></pre>
<pre><code>## Joining with `by = join_by(score, group)`</code></pre>
<pre class="r"><code>simluation_test1 &lt;- simulation %&gt;%
  group_by(group) %&gt;%
  specify(response = score) %&gt;% 
  generate(reps = 15000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;) %&gt;%
  ungroup()</code></pre>
<p>Commentary: turns out it just ignores the group_by, as the
bootstrapping provides means that encompass the entire data.</p>
<p>Commentary: Ok after talking to Mason on 4/16, we figured out this
question was intended for us to run a t-test.</p>
</div>
<div id="answer" class="section level5">
<h5>9 Answer</h5>
<pre class="r"><code>t.test(weight ~ habit, data = ncbirths_clean)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by habit
## t = 2.359, df = 171.32, p-value = 0.01945
## alternative hypothesis: true difference in means between group nonsmoker and group smoker is not equal to 0
## 95 percent confidence interval:
##  0.05151165 0.57957328
## sample estimates:
## mean in group nonsmoker    mean in group smoker 
##                7.144273                6.828730</code></pre>
<p>Based on the T-test, we know that mothers who don’t smoke have babies
with a higher weight (7.144) than mothers who smoke (6.829).</p>
</div>
</div>
<div
id="construct-a-95-confidence-interval-for-the-difference-between-the-average-weights-of-babies-born-to-smoking-and-non-smoking-mothers."
class="section level4">
<h4>10. Construct a 95% confidence interval for the difference between
the average weights of babies born to smoking and non-smoking
mothers.</h4>
<pre class="r"><code>mean_smoker_weight &lt;- mean(smoker_data$weight)
mean_nonsmoker_weight &lt;- mean(nonsmoker_data$weight)
sd_smoker_weight &lt;- sd(smoker_data$weight)
sd_nonsmoker_weight &lt;- sd(nonsmoker_data$weight)

mean_diff_smoker_weight &lt;- mean_nonsmoker_weight - mean_smoker_weight

se_smoker_weight &lt;- sqrt(sd_smoker_weight/nrow(smoker_data))+(sd_nonsmoker_weight/nrow(nonsmoker_data))


  
ci_diff &lt;- data.frame(
    mean_weight = mean_diff_smoker_weight,
    se = se_smoker_weight,
    lower = mean_diff_smoker_weight - 1.96 * se_smoker_weight,
    upper = mean_diff_smoker_weight + 1.96 * se_smoker_weight
  )

ci_diff</code></pre>
<pre><code>##   mean_weight        se    lower    upper
## 1   0.3155425 0.1066273 0.106553 0.524532</code></pre>
<p>The 95% CI for the mean difference between average weights is (.11
&lt; x &gt; .52).</p>
<p>Commentary: I know to use the SE, but I’m not sure if other people
do. Might want to give them the equation as scaffolding?</p>
</div>
<div
id="first-a-non-inference-task-determine-the-age-cutoff-for-younger-and-mature-mothers.-use-a-method-of-your-choice-and-explain-how-your-method-works."
class="section level4">
<h4>11. First, a non-inference task: Determine the age cutoff for
younger and mature mothers. Use a method of your choice, and explain how
your method works.</h4>
<pre class="r"><code>test_mature_upper_cutoff &lt;- ncbirths_clean %&gt;%
  filter(mature == &quot;mature mom&quot;)

min(test_mature_upper_cutoff$mage)</code></pre>
<pre><code>## [1] 35</code></pre>
<pre class="r"><code>test_mature_lower_cutoff &lt;- ncbirths_clean %&gt;%
  filter(mature == &quot;younger mom&quot;)

min(test_mature_lower_cutoff$mage)</code></pre>
<pre><code>## [1] 13</code></pre>
<p>I filtered based on mature mom’s and saw what the lowest age for
mature moms was. I did the same for young moms and looked at the maximum
age. Since they’re both 35, this will be the cutoff.</p>
</div>
<div
id="conduct-a-hypothesis-test-evaluating-whether-the-proportion-of-low-birth-weight-babies-is-higher-for-mature-mothers.-use-alpha-of-.05"
class="section level4">
<h4>12. Conduct a hypothesis test evaluating whether the proportion of
low birth weight babies is higher for mature mothers. Use alpha of
.05</h4>
<p>Commentary: I will note that this question assumes people got it
right originally.</p>
<p>Null: Mu1 - Mu2 = 0 OR Mu1 = Mu2 (No difference between mature
mothers on baby weight)</p>
<p>Alternate: Mu1 - Mu2 ≠ 0 OR Mu1 ≠ Mu2 (low birth weight babies is
higher for mature mothers)</p>
<pre class="r"><code>t_test_LBW &lt;- ncbirths %&gt;%
  mutate(lowbirthweight_numeric = case_when(
    lowbirthweight == &quot;not low&quot; ~ 0,
    lowbirthweight == &quot;low&quot; ~ 1
  ))

t.test(lowbirthweight_numeric ~ mature, data = t_test_LBW)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  lowbirthweight_numeric by mature
## t = 0.889, df = 166.59, p-value = 0.3753
## alternative hypothesis: true difference in means between group mature mom and group younger mom is not equal to 0
## 95 percent confidence interval:
##  -0.03427078  0.09041460
## sample estimates:
##  mean in group mature mom mean in group younger mom 
##                 0.1353383                 0.1072664</code></pre>
<p>Assuming I did this correctly, there is no difference between younger
and mature mothers for babies with low birth weight (p = .37)</p>
</div>
<div
id="calculate-a-confidence-interval-for-the-difference-between-the-proportions-of-low-birth-weight-babies-between-mature-and-younger-mothers.-interpret-the-interval-in-the-context-of-the-data-and-explain-what-it-means."
class="section level4">
<h4>13. Calculate a confidence interval for the difference between the
proportions of low birth weight babies between mature and younger
mothers. Interpret the interval in the context of the data and explain
what it means.</h4>
<pre class="r"><code>t_test_LBW &lt;- ncbirths %&gt;%
  mutate(lowbirthweight_numeric = case_when(
    lowbirthweight == &quot;not low&quot; ~ 0,
    lowbirthweight == &quot;low&quot; ~ 1
  ))

mature_low_weight &lt;- t_test_LBW %&gt;%
  filter(mature == &quot;mature mom&quot;)
young_low_weight &lt;- t_test_LBW %&gt;%
  filter(mature == &quot;younger mom&quot;)


prop_mature_low &lt;- mean(mature_low_weight$lowbirthweight_numeric)
prop_young_low &lt;- mean(young_low_weight$lowbirthweight_numeric)


diff_maturity_lowweight_mean &lt;- prop_mature_low - prop_young_low

diff_maturity_lowweight_sd &lt;- sqrt((1-prop_mature_low)/nrow(mature_low_weight)) + ((1-prop_young_low)/nrow(young_low_weight))


  
ci_lowweight_dif &lt;- data.frame(
    mean_weight = diff_maturity_lowweight_mean,
    se = diff_maturity_lowweight_sd,
    lower = diff_maturity_lowweight_mean - 1.96 * diff_maturity_lowweight_sd,
    upper = diff_maturity_lowweight_mean + 1.96 * diff_maturity_lowweight_sd
  )

ci_lowweight_dif</code></pre>
<pre><code>##   mean_weight        se      lower     upper
## 1  0.02807191 0.0816598 -0.1319813 0.1881251</code></pre>
<p>The CI is (-0.1319813, 0.1881251). Since the CI strattles zero, I
know it’s non-significant. If I had to guess what the CI represented, it
would represent how large the difference is between the probability of a
young mother giving birth to an underweight baby and an older mother
giving birth to an underweight baby.</p>
<p>Commentary: Learned SE when looking at proportions is (1-prop) for
each group instead of of the sd. Might be helpful to rewrite SE for
proportions or give students a hint to google it.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
