<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 08 - University of Edinburgh Art Collection</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="Aesthetics.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Benjamin Egan's Labs</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About Me</a>
</li>
<li>
  <a href="lab1.html">Lab 1</a>
</li>
<li>
  <a href="lab2.html">Lab 2</a>
</li>
<li>
  <a href="lab3.html">Lab 3</a>
</li>
<li>
  <a href="lab4.html">Lab 4</a>
</li>
<li>
  <a href="lab5.html">Lab 5</a>
</li>
<li>
  <a href="lab6.html">Lab 6</a>
</li>
<li>
  <a href="lab7.html">Lab 7</a>
</li>
<li>
  <a href="lab8.html">Lab 8</a>
</li>
<li>
  <a href="lab9.html">Lab 9</a>
</li>
<li>
  <a href="lab10.html">Lab 10</a>
</li>
<li>
  <a href="lab11.html">Lab 11</a>
</li>
<li>
  <a href="lab12.html">Lab 12</a>
</li>
<li>
  <a href="lab13.html">Lab 13</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lab 08 - University of Edinburgh Art
Collection</h1>

</div>


<div id="created-332025" class="section level4">
<h4>Created 3/3/2025</h4>
<p>link to assignment: <a
href="https://datascience4psych.github.io/DataScience4Psych/lab08.html"
class="uri">https://datascience4psych.github.io/DataScience4Psych/lab08.html</a></p>
<p>link to archived assignment: <a
href="https://web.archive.org/web/20250414135303/https://datascience4psych.github.io/DataScience4Psych/lab08.html#write-out-data"
class="uri">https://web.archive.org/web/20250414135303/https://datascience4psych.github.io/DataScience4Psych/lab08.html#write-out-data</a></p>
</div>
<div id="load-packages-and-data" class="section level2">
<h2>Load Packages and Data</h2>
<p>First, let’s load the necessary packages:</p>
<pre class="r"><code>library(tidyverse) 
library(dplyr)
library(skimr)
library(robotstxt) #use to see if can use paths_allowed</code></pre>
<pre><code>## Warning: package &#39;robotstxt&#39; was built under R version 4.3.3</code></pre>
<pre class="r"><code>library(rvest)
library(magrittr)</code></pre>
<pre><code>## Warning: package &#39;magrittr&#39; was built under R version 4.3.3</code></pre>
<pre class="r"><code>library(skimr)

paths_allowed(&quot;https://collections.ed.ac.uk/art)&quot;)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Now, load the dataset. If your data isn’t ready yet, you can leave
<code>eval = FALSE</code> for now and update it when needed.</p>
<pre class="r"><code>uoe_art &lt;- read_csv(&quot;./data/uoe-art.csv&quot;)
view(uoe_art)</code></pre>
</div>
<div id="exercise-9" class="section level2">
<h2>Exercise 9</h2>
<p>Let’s start working with the <strong>title</strong> column by
separating the title and the date:</p>
<pre class="r"><code>uoe_art &lt;- uoe_art %&gt;%
  separate(title, into = c(&quot;title&quot;, &quot;date&quot;), sep = &quot;\\(&quot;) %&gt;%
  mutate(year = str_remove(date, &quot;\\)&quot;) %&gt;% as.numeric()) %&gt;%
  dplyr::select(title, artist, year, link)</code></pre>
<pre><code>## Warning: Expected 2 pieces. Additional pieces discarded in 47 rows
## [182, 195, 209, 533, 729, 732, 771, 775, 781, 879, 982,
## 1029, 1041, 1045, 1132, 1176, 1279, 1336, 1358, 1359,
## ...].</code></pre>
<pre><code>## Warning: Expected 2 pieces. Missing pieces filled with `NA` in 697
## rows [4, 15, 17, 22, 26, 27, 30, 31, 32, 34, 39, 41, 44,
## 53, 58, 63, 78, 82, 86, 93, ...].</code></pre>
<pre><code>## Warning: There was 1 warning in `mutate()`.
## ℹ In argument: `year = str_remove(date, &quot;\\)&quot;) %&gt;%
##   as.numeric()`.
## Caused by warning in `str_remove(date, &quot;\\)&quot;) %&gt;% as.numeric()`:
## ! NAs introduced by coercion</code></pre>
<pre class="r"><code>#Note select() is being overrode by other packages, such as MASS.</code></pre>
<p>The code was already provided, so I didn’t change anything. I’m
guessing the error related to “expected two pieces” is because not all
pieces had both a year and an author. I can see no author in some rows
(182, 533, etc.) but not in all of them. I’m also guessing that they
filled in these missing pieces with “NA.” There were probably rows that
didn’t have parentheses around years, adding to the confusion. One of
the rows just gave us a “2” for the year, probably adding to the
confusion about including the year.</p>
<pre class="r"><code>skim(uoe_art)</code></pre>
<table>
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">uoe_art</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">3312</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">4</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">3</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<colgroup>
<col width="19%" />
<col width="13%" />
<col width="19%" />
<col width="5%" />
<col width="5%" />
<col width="8%" />
<col width="12%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">title</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0</td>
<td align="right">95</td>
<td align="right">5</td>
<td align="right">1629</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">artist</td>
<td align="right">111</td>
<td align="right">0.97</td>
<td align="right">2</td>
<td align="right">55</td>
<td align="right">0</td>
<td align="right">1198</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">link</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">45</td>
<td align="right">48</td>
<td align="right">0</td>
<td align="right">3312</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<colgroup>
<col width="17%" />
<col width="12%" />
<col width="17%" />
<col width="9%" />
<col width="7%" />
<col width="3%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year</td>
<td align="right">1580</td>
<td align="right">0.52</td>
<td align="right">1964.56</td>
<td align="right">53.22</td>
<td align="right">2</td>
<td align="right">1953</td>
<td align="right">1962</td>
<td align="right">1977</td>
<td align="right">2020</td>
<td align="left">▁▁▁▁▇</td>
</tr>
</tbody>
</table>
<pre class="r"><code>uoe_art %&gt;%
  ggplot(aes(
    x = year
  ))+
  geom_bar()</code></pre>
<pre><code>## Warning: Removed 1580 rows containing non-finite outside the scale
## range (`stat_count()`).</code></pre>
<p><img src="lab8_files/figure-html/skim-1.png" width="672" /></p>
<pre class="r"><code>summary(uoe_art)</code></pre>
<pre><code>##     title              artist               year          link          
##  Length:3312        Length:3312        Min.   :   2   Length:3312       
##  Class :character   Class :character   1st Qu.:1953   Class :character  
##  Mode  :character   Mode  :character   Median :1962   Mode  :character  
##                                        Mean   :1965                     
##                                        3rd Qu.:1977                     
##                                        Max.   :2020                     
##                                        NA&#39;s   :1580</code></pre>
<p>Using skim(), it appears that there are 111 artists missing from the
data frame. It also appears there are 1580 data missing from the year
column. One of the paintings shows a painting to be from the year 2.
Death mask had an additional number in the sequence. The year should be
1964.</p>
<pre class="r"><code>#Change year for Death Mask
uoe_art_fixed &lt;- uoe_art %&gt;%
  mutate(year = case_when(
    year == &quot;2&quot; ~ &quot;1964&quot;,
    .default = as.character(year)
  ))
view(uoe_art_fixed)



uoe_art_fixed &lt;- uoe_art_fixed %&gt;%
  mutate(decade = cut(as.numeric(year), 
                        breaks = seq(1810, 2030, by = 10), 
                        labels = seq(1810, 2020, by = 10), 
                        right = TRUE))


 ggplot(data=subset(
   uoe_art_fixed,
   !is.na(decade)), 
   aes(x=decade))+
  geom_bar()+
   labs(
     x = &quot;Artworks in a year by decade&quot;,
     y = &quot;Count&quot;,
     title = &quot;Endinborough Art Collection&quot;
   )</code></pre>
<p><img src="lab8_files/figure-html/filter-1.png" width="672" /></p>
<p>Here I used a subset of the data that got rid of the missing years
and binned years to create decades. We can see there are a lot of
artwork created in the mid 1900s.</p>
<div id="artist-breakdown" class="section level3">
<h3>Artist breakdown</h3>
<pre class="r"><code>uoe_art_fixed %&gt;%
  count(artist, sort = TRUE)</code></pre>
<pre><code>## # A tibble: 1,199 × 2
##    artist               n
##    &lt;chr&gt;            &lt;int&gt;
##  1 Unknown            373
##  2 Emma Gillies       175
##  3 &lt;NA&gt;               111
##  4 Ann F Ward          23
##  5 John Bellany        22
##  6 Zygmunt Bukowski    21
##  7 Boris Bućan         17
##  8 Marjorie Wallace    17
##  9 Gordon Bryce        16
## 10 William Gillon      16
## # ℹ 1,189 more rows</code></pre>
<p>The most common artist is unknown! This is followed by Emma Gillies
and N/A. Apparently this database doesn’t know a lot about their
artworks.</p>
</div>
<div id="art-about-children" class="section level3">
<h3>Art about children</h3>
<pre class="r"><code>filter(uoe_art_fixed, str_detect(uoe_art_fixed$title, &quot;Child&quot;) == TRUE)</code></pre>
<pre><code>## # A tibble: 11 × 5
##    title                                               artist year  link  decade
##    &lt;chr&gt;                                               &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt; &lt;fct&gt; 
##  1 &quot;The Sun Dissolves while Man Looks Away from the U… Eduar… &lt;NA&gt;  coll… &lt;NA&gt;  
##  2 &quot;Virgin and Child&quot;                                  Unkno… &lt;NA&gt;  coll… &lt;NA&gt;  
##  3 &quot;Virgin and Child &quot;                                 Unkno… &lt;NA&gt;  coll… &lt;NA&gt;  
##  4 &quot;Woman with Child and Still Life &quot;                  Cathe… 1938  coll… 1930  
##  5 &quot;Virgin and Child &quot;                                 Unkno… &lt;NA&gt;  coll… &lt;NA&gt;  
##  6 &quot;Child&#39;s collar. Chinese&quot;                           Unkno… &lt;NA&gt;  coll… &lt;NA&gt;  
##  7 &quot;Child&#39;s chinese headdress&quot;                         Unkno… &lt;NA&gt;  coll… &lt;NA&gt;  
##  8 &quot;Figure Composition with Nurse and Child, and Woma… Edwar… &lt;NA&gt;  coll… &lt;NA&gt;  
##  9 &quot;Untitled - Children Playing &quot;                      Monik… 1963  coll… 1960  
## 10 &quot;The Children&#39;s Hour &quot;                              Eduar… &lt;NA&gt;  coll… &lt;NA&gt;  
## 11 &quot;Untitled - Portrait of a Woman and Child &quot;         Willi… &lt;NA&gt;  coll… &lt;NA&gt;</code></pre>
<p>I found all cases where the title contained child and filtered for
them. There are 11 total titles containing child/children.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
